version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    image: registry.digitalocean.com/clutchbids-registry/best-value-auctions:latest
    container_name: best-value-auctions